import House1 from "../../../public/house/house1.jpg";
import House2 from "../../../public/house/house2.jpg";
import House3 from "../../../public/house/house3.jpg";
import House4 from "../../../public/house/house4.webp";
import House5 from "../../../public/house/house5.jpg";

export const Data = [
    {
      id: 1,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House1, House2, House3, House4, House5],
      activeImageIndex: 0,
    },
    {
      id: 2,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House2, House3, House4, House5, House1],
      activeImageIndex: 0,
    },
    {
      id: 3,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House3, House4, House5, House1, House2],
      activeImageIndex: 0,
    },
    {
      id: 4,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House4, House5, House1, House2, House3],
      activeImageIndex: 0,
    },
    {
      id: 5,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House3, House2, House3, House4, House5],
      activeImageIndex: 0,
    },
    {
      id: 6,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House4, House3, House4, House5, House1],
      activeImageIndex: 0,
    },
    {
      id: 7,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House1, House4, House5, House1, House2],
      activeImageIndex: 0,
    },
    {
      id: 8,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House5, House5, House1, House2, House3],
      activeImageIndex: 0,
    },
    {
      id: 9,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House5, House2, House3, House4, House5],
      activeImageIndex: 0,
    },
    {
      id: 10,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House4, House3, House4, House5, House1],
      activeImageIndex: 0,
    },
    {
      id: 11,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House3, House4, House5, House1, House2],
      activeImageIndex: 0,
    },
    {
      id: 12,
      name: "Lotus - Prime Apartment",
      rent: "13,785",
      rating: "Good",
      star: "4.1",
      images: [House2, House5, House1, House2, House3],
      activeImageIndex: 0,
    },
  ];